<div class="instagram-feed">
    <a href="https://www.instagram.com/p/CWYGXqTM7jQ/" class="css-llkgph">
        <div class="gatsby-image-wrapper">
            <img src="https://xwander.fi/wp-content/uploads/2021/11/257231049_3064477097144898_3827585969641007434_n.jpg" alt="The nature of Lapland has the power to calm you down with its raw simplicity. We all need and deserve breaks like these!#outdoors #wanderlust #explore #getoutside #ulkonaperillä #amazingviews  #amazingplaces #beautifulnaturepic  #wondermore #lapland #finland #visitlapland #lappi #kiilopää #finnishmoments #munlappi #inari">
        </div>
        <p class="chakra-text css-jr9l3h">The nature of Lapland has the power to calm you down with its raw simplicity. We all need and deserve breaks like these!#outdoors #wanderlust #explore #getoutside #ulkonaperillä #amazingviews #amazingplaces #beautifulnaturepic #wondermore #lapland #finland #visitlapland #lappi #kiilopää #finnishmoments #munlappi #inari</p>
    </a>
    <a href="https://www.instagram.com/p/CVz2gkrsh5M/" class="css-llkgph">
        <div class=" gatsby-image-wrapper">
            <img src="https://xwander.fi/wp-content/uploads/2021/11/252177204_3244697879090992_9091800390278222823_n.jpg" alt="Lapinhulluus? Vietä arktinen unelmaloma ja koe itse mikä pohjoisessa oikein viehättää. Miniloma Ivalossa on täydellinen paketti, joka sisältää kaikki Lapin parhaat elämykset, kuten huskysafarin, porojen silittelyä, tunturimaisemat, hyvää ruokaa ja saamelaiskulttuuria! Lue sivuiltamme lisää: https://xwander.fi/fi/miniloma-ivalossa #huskysafari #lappi #lapland #suomi #nature #luonto #visitfinland #luontoonfi #tunturi #matkailu #kotimaanmatkailu #poro #munlappi #ourfinland #lomalle #loma #matkusta">
        </div>
        <p class="chakra-text css-jr9l3h">Lapinhulluus? Vietä arktinen unelmaloma ja koe itse mikä pohjoisessa oikein viehättää. Miniloma Ivalossa on täydellinen paketti, joka sisältää kaikki Lapin parhaat elämykset, kuten huskysafarin, porojen silittelyä, tunturimaisemat, hyvää ruokaa ja saamelaiskulttuuria! Lue sivuiltamme lisää: https://xwander.fi/fi/miniloma-ivalossa #huskysafari #lappi #lapland #suomi #nature #luonto #visitfinland #luontoonfi #tunturi #matkailu #kotimaanmatkailu #poro #munlappi #ourfinland #lomalle #loma #matkusta</p>
    </a>
    <a href="https://www.instagram.com/p/CU7Cl1osSAo/" class="css-llkgph">
        <div class=" gatsby-image-wrapper">
            <img src="https://xwander.fi/wp-content/uploads/2021/11/244769949_123560416710850_7040670622659610619_n.jpg" alt="Kaipaatko irtiottoa arjesta? Haluasitko tulla huoltamaan kehoa ja mieltä Lapin sydämeen? 💜 Lämpimästi tervetuloa Hyvinvointilomalle Ivaloon joulukuussa! Joogaa &amp; Mindfulnessia kokeneen ohjaajan johdolla. Omaa aikaa ja rentoutumista. Kävelyä ja lumikenkäilyä upeissa tunturimaisemissa Saariselällä sekä metsäretkellä Inarin Tuulisjärvellä. Retkilounaat maistuvat avotulella. Saunomista ja mahdollisuus pulahtaa avantoon. Majoitus Xwanderin viihtyisissä asunnoissa Ivalon kylällä. Et tarvitse aiempaa kokemusta joogasta, harjoitukset sopivat kaikille ja räätälöidään osallistujien tason mukaan. Tervetuloa mukaan! 🙏🏼 Lisätietoja : https://xwander.fi/fi/talvinen-hyvinvointiloma-ivalo #jooga #joogasuomi #lappi #mindfulness #hyvinvointi #visitfinland #retriitti #meditaatio #tasapaino #omavoima #luonnonrauha #joogajokapäivä #ivalo #palautuminen #hyväolo #matkustus #stressinhallinta #inari">
        </div>
        <p class="chakra-text css-jr9l3h">Kaipaatko irtiottoa arjesta? Haluasitko tulla huoltamaan kehoa ja mieltä Lapin sydämeen? 💜 Lämpimästi tervetuloa Hyvinvointilomalle Ivaloon joulukuussa! Joogaa &amp; Mindfulnessia kokeneen ohjaajan johdolla. Omaa aikaa ja rentoutumista. Kävelyä ja lumikenkäilyä upeissa tunturimaisemissa Saariselällä sekä metsäretkellä Inarin Tuulisjärvellä. Retkilounaat maistuvat avotulella. Saunomista ja mahdollisuus pulahtaa avantoon. Majoitus Xwanderin viihtyisissä asunnoissa Ivalon kylällä. Et tarvitse aiempaa kokemusta joogasta, harjoitukset sopivat kaikille ja räätälöidään osallistujien tason mukaan. Tervetuloa mukaan! 🙏🏼 Lisätietoja : https://xwander.fi/fi/talvinen-hyvinvointiloma-ivalo #jooga #joogasuomi #lappi #mindfulness #hyvinvointi #visitfinland #retriitti #meditaatio #tasapaino #omavoima #luonnonrauha #joogajokapäivä #ivalo #palautuminen #hyväolo #matkustus #stressinhallinta #inari</p>
    </a>
    <a href="https://www.instagram.com/p/CUEwB_YMLI5/" class="css-llkgph">
        <div class=" gatsby-image-wrapper">
            <img src="https://xwander.fi/wp-content/uploads/2021/11/242495959_361054558800989_7949454565633624444_n.jpg" alt="A show like no other! Lapland is giving its best right now and we can’t help but go out! #nellim #ruska #autumn #autumnvibes #autumnvibes🍁 #nature #naturephotography #landscape #photography #outdoors #wanderlust #explore #getoutside #ulkonaperillä #lapland #finland #visitlapland #lappi #ourlapland #finnishnature #finnishmoments #ourfinland #onlyinlapland #laponie #finlandia #finland #suomenluonto #thisisfinland #kotimaassa #munlappi #inari">
        </div>
        <p class="chakra-text css-jr9l3h">A show like no other! Lapland is giving its best right now and we can’t help but go out! #nellim #ruska #autumn #autumnvibes #autumnvibes🍁 #nature #naturephotography #landscape #photography #outdoors #wanderlust #explore #getoutside #ulkonaperillä #lapland #finland #visitlapland #lappi #ourlapland #finnishnature #finnishmoments #ourfinland #onlyinlapland #laponie #finlandia #finland #suomenluonto #thisisfinland #kotimaassa #munlappi #inari</p>
    </a>
    <a href="https://www.instagram.com/p/CTwQ4P1Mmil/" class="css-llkgph">
        <div class=" gatsby-image-wrapper">
            <img src="https://xwander.fi/wp-content/uploads/2021/11/242022391_607352263616624_5446429040445961165_n.jpg" alt="The peak of “ruska”!! Right now we can admire the intense colors of autumn. Lapland is so famous of its beauty during this time of the year, we even have a special word for it in Finnish 🧡💛🍂🍁🍄 Enjoy the RUSKA as much as you can everybody!  #ruska #autumn #autumnvibes🍁 #nature #naturephotography #naturelovers #landscape #landscapephotography #outdoors #wanderlust #explore #getoutside #wondermore #lapland #finland #visitlapland #lappi  #ourlapland #explorefinland #finnishmoments #ourfinland #lovelyfinland #onlyinlapland #laponie #finlandia #finland #suomenluonto #thisisfinland #munlappi #inari">
        </div>
        <p class="chakra-text css-jr9l3h">The peak of “ruska”!! Right now we can admire the intense colors of autumn. Lapland is so famous of its beauty during this time of the year, we even have a special word for it in Finnish 🧡💛🍂🍁🍄 Enjoy the RUSKA as much as you can everybody! #ruska #autumn #autumnvibes🍁 #nature #naturephotography #naturelovers #landscape #landscapephotography #outdoors #wanderlust #explore #getoutside #wondermore #lapland #finland #visitlapland #lappi #ourlapland #explorefinland #finnishmoments #ourfinland #lovelyfinland #onlyinlapland #laponie #finlandia #finland #suomenluonto #thisisfinland #munlappi #inari</p>
    </a>
    <a href="https://www.instagram.com/p/CSY3xMVDfNk/" class="css-llkgph">
        <div class=" gatsby-image-wrapper">
            <img src="https://xwander.fi/wp-content/uploads/2021/11/234800608_4623370121015087_98068800825050111_n.jpg" alt="🍂 Looking forward to see the full glory of autumn in Lapland, the first signs are already there! Kauan odotetun Lapin ruskan ensimmäiset merkit! #nature #naturephotography #natureaddict #outdoors #wanderlust #explore #naturelovers #wandern #getoutside #retkellä #ulkonaperillä #lapland #finland #visitlapland #lappi #visitfinland #ourlapland #finnishnature  #ourfinland #luontoonfi #munlappi #tunturissaonhyväolla #kotimaassa #ruska">
        </div>
        <p class="chakra-text css-jr9l3h">🍂 Looking forward to see the full glory of autumn in Lapland, the first signs are already there! Kauan odotetun Lapin ruskan ensimmäiset merkit! #nature #naturephotography #natureaddict #outdoors #wanderlust #explore #naturelovers #wandern #getoutside #retkellä #ulkonaperillä #lapland #finland #visitlapland #lappi #visitfinland #ourlapland #finnishnature #ourfinland #luontoonfi #munlappi #tunturissaonhyväolla #kotimaassa #ruska</p>
    </a>
</div>